theme: jekyll-theme-minimal
#markdown: CommonMarkGhPages
title: CCA-crate-profile
email: rpalma@man.poznan.pl
description: > # this means to ignore newlines until "baseurl:" 
  Climate change adaptation RO crate profile 
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://about.workflowhub.eu" # the base hostname & protocol for your site
#github_username:  RELIANCE-EOSC
#encoding: UTF-8
#permalink: pretty

logo: images/FAIR2Adapt_logo.png